### PR TITLE
forum added to navigation

### PR DESCRIPTION
**Pull request by marianorod**
closes https://github.com/bitpay/bitcore/issues/1017

### CODE REVIEW

**Comment by maraoz** [comment]
LGTM

**Comment by braydonf** [comment]
"API" I think should remain as "API" and not "Api". Since it's an acronym.

**Comment by braydonf** [comment]
As an aside: The icon looks somewhat like a torch, not a test tube. Furthermore it's a forum, and not really an area of research projects. Perhaps this is more a question in general domain and name of the site? @bitjson

**Comment by marianorod** [comment]
"Api" changed into "API"
The logo is the one for Bitpay Labs

**Comment by maraoz** [comment]
ACK

**Pull request merged**
